# Generated by Django 5.0.4 on 2024-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
