# Generated by Django 5.0.4 on 2024-04-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
