# Generated by Django 5.0.4 on 2024-05-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
